name: Configuration Check
on:
  repository_dispatch:
    types:
      - custom-build

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: echo "$API_IP"
        shell: bash
        env:
          API_IP: ${{ github.event.client_payload.api_ip }}