name: Configuration Check
on:
  repository_dispatch:
    types:
      - custom-build

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: echo "$API_IP"
        shell: bash
        env:
          API_IP: ${{ github.event.client_payload.api_ip }}

      - name: App Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.api_ip }}

      - run:  |
          sed -i -e 's/const\sval\sAPI_QA\s=\s"13.229.188.140|v2"/const\sval\sAPI_QA\s=\s"52.221.203.54|v2"/g' $FILE_PATH
          cat $FILE_PATH
        shell: bash
        env:
          FILE_PATH: app/src/main/java/com/hk/ijournal/common/CommonLib.kt